### ISSUE TITLE
encode openlr

### ISSUE THREAD

**Issue by guyanf** [tomtom-international/openlr-python#11]
Hi guys.
How can I convert an XML(openlr) to binary data! (Used openlr-python)
Thanks!

**Comment by aksakalli** [comment]
Hi,
You can use one of the following functions to read from xml:
* [xml_decode_file](https://github.com/tomtom-international/openlr-python/blob/3bc863e1fc2182888bf4dc1a6b4937d06b4aa406/openlr/xml_format.py#L57)
* [xml_decode_string](https://github.com/tomtom-international/openlr-python/blob/3bc863e1fc2182888bf4dc1a6b4937d06b4aa406/openlr/xml_format.py#L63)
* [xml_decode_document](https://github.com/tomtom-international/openlr-python/blob/3bc863e1fc2182888bf4dc1a6b4937d06b4aa406/openlr/xml_format.py#L69)

and to convert back to binary:
* [binary_encode](https://github.com/tomtom-international/openlr-python/blob/3bc863e1fc2182888bf4dc1a6b4937d06b4aa406/openlr/binary_format.py#L107)

```python
import openlr

xml_input = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OpenLR xmlns="http://www.openlr.org/openlr">
  <LocationID></LocationID>
  <XMLLocationReference>
    <PointLocationReference>
      <GeoCoordinate>
        <Coordinates>
          <Longitude>-34.60893988592811</Longitude>
          <Latitude>-58.373268842418796</Latitude>
        </Coordinates>
      </GeoCoordinate>
    </PointLocationReference>
  </XMLLocationReference>
</OpenLR>
"""
location = openlr.xml_decode_string(xml_input)
print(location)  # GeoCoordinateLocationReference(point=Coordinates(lon=-34.60893988592811, lat=-58.373268842418796))

binary = openlr.binary_encode(location)
print(binary)  # I+djotZ9eA==
```
