### ISSUE TITLE
a comment error

### ISSUE THREAD

**Issue by guyanf** [tomtom-international/openlr-python#14]
#### Environment

- OS:
- Python version: 3.9
- openlr version: 1.0.1

#### Description

*A description of the issue*

Hi,guys.

code in "openlr_bytes_io.py"

def int_to_deg(val, resolution=24):
    r"""converts degree coordinate into integer

may be comment is "converts integer into degree coordinate  "

thanks.

**Comment by aksakalli** [comment]
Thanks for pointing that. Indeed, it needs to be fixed. Do you want to send a PR for it?

**Comment by guyanf** [comment]
Hi aksakalli.

**Comment by guyanf** [comment]
Hi aksakalli.
Sorry, I don't known how to pull a request.
You may need to fix it. Thanks.

Thomas

**Comment by aksakalli** [comment]
Hey Thomas,

You can create a PR using the Web UI as well. You would need to go to the [openlr_bytes_io.py](https://github.com/tomtom-international/openlr-python/blob/master/openlr/openlr_bytes_io.py) file and click the pen icon which says `fork this project and edit the file` and follow [the steps](https://docs.github.com/en/github/managing-files-in-a-repository/managing-files-on-github/editing-files-in-another-users-repository). It would create PR for you when you save your changes.

**Comment by guyanf** [comment]
Hi aksakalli.
Thank you. I made it
Thomas
