### ISSUE TITLE
module 'openlr' has no attribute 'GeoCoordinateLocation'

### ISSUE THREAD

**Issue by mbob001** [tomtom-international/openlr-python#16]
#### Environment

- OS: Windows 10
- Python version: Python 3.9.1
- openlr version: 1.0.1

#### Description

I tried to run your example:
`import openlr

location = openlr.GeoCoordinateLocation(
    openlr.Coordinates(52.495218, 13.461668)
)

print(openlr.binary_encode(location))  # IyVUdwmSoA==
print(openlr.xml_encode_to_string(location))  # <?xml version="1.0" ?><OpenLR ...`

I get an error: module 'openlr' has no attribute 'GeoCoordinateLocation' in this line: location = openlr.GeoCoordinateLocation(...

Other examples working perfectly.
Thanks.

**Comment by aksakalli** [comment]
Hi,

Thank you for reporting. Indeed #6 did not change the getting started Guide properly. It is supposed to be [GeoCoordinateLocationReference](https://openlr-python.readthedocs.io/en/latest/reference.html#openlr.GeoCoordinateLocationReference). Would you like to send a [pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) to fix this issue?

**Comment by mbob001** [comment]
Thanks, it is not necessary.

**Comment by aksakalli** [comment]
I think it's necessary for the project. :) 

A small change in [getting-started.rst](https://github.com/tomtom-international/openlr-python/blob/master/docs/getting-started.rst). I would really appreciate your contribution but it's of course no problem if you don't.

**Comment by aksakalli** [comment]
solved with #17
